server:
  port: 8081

spring:
  application:
    name: user-service
  datasource:
    url: jdbc:postgresql://localhost:5432/rideflow_users
    username: rideflow
    password: rideflow
  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false

  flyway:
    enabled: true
    locations: classpath:db/migration


rideflow:
  jwt:
    secret: ${RIDEFLOW_JWT_SECRET:local-dev-only-secret-change-me-0123456789}

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

management:
  endpoints:
    web:
      exposure:
        include: health, info
  endpoint:
    health:
      show-details: always

logging:
  level:
    org.hibernate.SQL: INFO
